name: Terraform Apply

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Debug Environment Variables
        run: |
          echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
          echo "AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:0:4}********"
          echo "AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION"
          echo "DB_PASSWORD: ${DB_PASSWORD:0:2}********"
          env
          echo "Current directory: $(pwd)"
          ls -l
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Plan
        run: terraform plan -var="db_password=$DB_PASSWORD" -out=tfplan
      
      - name: Terraform Apply
        run: terraform apply tfplan
      
      - name: Terraform Output
        id: terraform-output
        run: |
          echo "db_endpoint=$(terraform output -raw db_endpoint)" >> $GITHUB_OUTPUT
          echo "web_server_ip=$(terraform output -raw web_server_ip)" >> $GITHUB_OUTPUT 